### ISSUE TITLE
Doc is a huge pile of crap

### ISSUE THREAD

**Issue by Kixunil** [debian-cryptoanarchy/cryptoanarchy-deb-repo-builder#103]
**Have you actually read the documentation?**
Yes. (Please, go read the documentation first if you did not.)

**How would you ask about this?**
How am I supposed to run applications?

**What the documentation says**
"Do understand that bitcoind and other services will run automatically"

**What appears to be the correct documentation**
Big red sign that they run immediately after installation and each boot

**Comment by Kixunil** [comment]
We need to somehow verify that the docs makes sense, this can't continue, so far everyone screwed it up.

**Comment by henkvantijen** [comment]
Please someone open a Telegram group to discuss this Repo.  (I would do it myself, but I have reached max number of groups tow own in Telegram).

**Comment by Kixunil** [comment]
Done, it's called `CryptoanarchyDebRepo`.
