### ISSUE TITLE
Upgrade Bitcoind to 0.21

### ISSUE THREAD

**Issue by Kixunil** [debian-cryptoanarchy/cryptoanarchy-deb-repo-builder#110]
TAPROOOOOT!!!!

Seriously:

- [x] create a notify script
- [x] use `systemd-notify`
- [x] remove need_reindex marker #106 
- [x] **test every application!** - must not go to beta unless everything works

**Comment by Kixunil** [comment]
The version 0.21.1 is now in experimental. This seems to work.

**Comment by MaxHillebrand** [comment]
tested experimental with bitcoind 0.21.1, btcpay, lnd, & thunderhub in a fresh dispVM.
Everything went well, did not notice anything fishy.

**Comment by Kixunil** [comment]
Sadly, I hit some problems in when restarting bitcoind. I will try to set restart delay and see if it helps.

**Comment by Kixunil** [comment]
Looks like the delay helped, it's not getting stuck anymore. The new version is in experimental.

**Comment by MaxHillebrand** [comment]
tested bitcoind with restart, and it seems to work.

**Comment by Kixunil** [comment]
This is already in beta, forgot to close.

It still gets stuck in dispvm if the OS is under load. Most likely Qubes/regtest related. If anyone has this problem either on mainnet or outside Qubes, please LMK ASAP!
