### ISSUE TITLE
bitcoin-mainnet failed to start

### ISSUE THREAD

**Issue by martin1551** [debian-cryptoanarchy/cryptoanarchy-deb-repo-builder#150]
After sucessfully running bitcoin full node with bitcoin-mainnet it stopped working. I found this in log:

martin@ubuntu-nas:~$ sudo systemctl status bitcoin-mainnet
● bitcoin-mainnet.service - Bitcoin fully validating node
     Loaded: loaded (/lib/systemd/system/bitcoin-mainnet.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2021-04-27 00:20:28 CEST; 1min 18s ago
    Process: 21291 ExecStart=/usr/share/bitcoind/bitcoind -conf=/etc/bitcoin-mainnet/bitcoin.conf (code=exited, status=1/FAILURE)
   Main PID: 21291 (code=exited, status=1/FAILURE)

Apr 27 00:20:28 ubuntu-nas systemd[1]: bitcoin-mainnet.service: Main process exited, code=exited, status=1/FAILURE
Apr 27 00:20:28 ubuntu-nas systemd[1]: bitcoin-mainnet.service: Failed with result 'exit-code'.
Apr 27 00:20:28 ubuntu-nas systemd[1]: bitcoin-mainnet.service: Scheduled restart job, restart counter is at 12.
Apr 27 00:20:28 ubuntu-nas systemd[1]: Stopped Bitcoin fully validating node.
Apr 27 00:20:28 ubuntu-nas systemd[1]: bitcoin-mainnet.service: Start request repeated too quickly.
Apr 27 00:20:28 ubuntu-nas systemd[1]: bitcoin-mainnet.service: Failed with result 'exit-code'.
Apr 27 00:20:28 ubuntu-nas systemd[1]: Failed to start Bitcoin fully validating node.
martin@ubuntu-nas:~$ sudo journalctl -u bitcoin-mainnet --follow
-- Logs begin at Sun 2020-11-15 04:30:30 CET. --
Apr 27 00:20:28 ubuntu-nas bitcoind[21291]: EXCEPTION: N5boost10filesystem16filesystem_errorE
Apr 27 00:20:28 ubuntu-nas bitcoind[21291]: boost::filesystem::status: Permission denied: "/home/martin/share/data3/var/lib/bitcoin-mainnet"
Apr 27 00:20:28 ubuntu-nas bitcoind[21291]: bitcoin in AppInit()
Apr 27 00:20:28 ubuntu-nas systemd[1]: bitcoin-mainnet.service: Main process exited, code=exited, status=1/FAILURE
Apr 27 00:20:28 ubuntu-nas systemd[1]: bitcoin-mainnet.service: Failed with result 'exit-code'.
Apr 27 00:20:28 ubuntu-nas systemd[1]: bitcoin-mainnet.service: Scheduled restart job, restart counter is at 12.
Apr 27 00:20:28 ubuntu-nas systemd[1]: Stopped Bitcoin fully validating node.
Apr 27 00:20:28 ubuntu-nas systemd[1]: bitcoin-mainnet.service: Start request repeated too quickly.
Apr 27 00:20:28 ubuntu-nas systemd[1]: bitcoin-mainnet.service: Failed with result 'exit-code'.
Apr 27 00:20:28 ubuntu-nas systemd[1]: Failed to start Bitcoin fully validating node.

**System**
Ubuntu 20.04.2 LTS (focal)

**Comment by Kixunil** [comment]
This is not a *build* bug, you didn't attempt to build it...

Did you set custom location of bitcoind data dir? Which value did you set it to?

**Comment by martin1551** [comment]
Yes - custom location of bitcoind data dir. This is in my bitcoin.conf file:
datadir=/home/martin/share/data3/var/lib/bitcoin-mainnet

It used to work without any problems before running memtester after adding new RAM module. I don't see how this could relate, but just for the record.

**Comment by Kixunil** [comment]
Did you intentionally set the `/var/lib` part? You might have it needlessly deep. But that's not a problem.

I just realized this was caused by new update which sets `ProtectHome`. It didn't occur to me that someone would set datadir to `/home/...` as changing it was supposed to be used for external drives only - they are normally mounted in `/media`.

I will look into enabling access to datadir regardless of other settings. In the meantime, you may disable the protection - run:

```
systemctl edit bitcoin-mainnet
```

Enter this content:

```
[Service]
ProtectHome=false
```

Save and exit.

If you decide to move the directory somewhere outside `/home` instead please follow the procedure explained in https://github.com/debian-cryptoanarchy/cryptoanarchy-deb-repo-builder/blob/master/docs/admin-level.md#automation

**Comment by martin1551** [comment]
Thank you for the fix - temporary workaround fixed it.

**Comment by Kixunil** [comment]
Great! I opened #153 which more clearly describes the issue.
