### ISSUE TITLE
Publish new BTCPayServer package

### ISSUE THREAD

**Issue by dr-orlovsky** [debian-cryptoanarchy/cryptoanarchy-deb-repo-builder#212]
Current debian package version is 1.3.6-1, while in this repo it is 1.6.11-1.

Can a new version of the package be released to the debian repo?

**Comment by Kixunil** [comment]
Sorry, missed this issue. I plan to move it from experimental to beta soon, I just wanted to do some more testing. It's definitely high importance since it improves the reliability of connecting to LND **a lot**.

**Comment by Kixunil** [comment]
Found an issue: wrong link when opening from dahsboard. Easy to fix but I have some other things to do rn.

**Comment by Kixunil** [comment]
The newest version of BTCPay is now in beta.
